services:
  mysql:
    user: 501:20
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - /Users/kimkyungmin/Desktop/vsc_study/mysql_data:/var/lib/mysql:rw
      - /Users/kimkyungmin/Desktop/vsc_study/wanted-preonboarding-challenge-backend-16/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wanted


